config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  # get 'users/index'
  # get 'users/show'
  # get 'users/new'
  # get 'users/create'
  # get 'toppages/index'
    resources :works
    # root to: 'toppages#index'
    root to: 'works#index'
    # root to:'toppages#index'
    get 'signup', to: 'users#new'
    get 'login', to:'sessions#new'
    post 'login', to:'sessions#create'
    delete 'logout', to:'sessions#destroy'

    resources :users, only: [:index, :show, :new, :create] do
      member do
        get :followings
        get :followers
      end
      collection do
        get  :search
      end
      
    end
    resources :relationships, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow ,class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord

 before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    
                    uniqueness: { case_sensitive: false }
  has_secure_password    
  has_many :works
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
   has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  def follow(other_user)
   unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
   end
  end
   
  def unfollow(other_user)
   relationship=self.relationships.find_by(follow_id: other_user.id)
   relationship.destroy if relationship
  end
  
  def following?(other_user)
   self.followings.include?(other_user)
  end
end

app/models/work.rb
class Work < ApplicationRecord
    belong_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    
    private
    def require_user_logged_in
        unless logged_in?
               redirect_to login_url
        end
    end
    
    def counts(user)
        @count_tasks= user.tasks.count
        @count_following = user.followings.count
        @coount_follower = user.follower.count
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
        user =User.find(params:[:follow_id])
        current_user.follow(user)
        flash[:sucess]='フォローしました'
        redirect_to user
    end
    def destroy
        user=User.find(params[:follow_id])
        current_user.unfollow(user)
        flash[:success]='ユーザーのフォローを解除した'
        redirect_to user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index,:show]
  
  def index
    @users= User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user= User.find(params[:id])
  end

  def new
    @user=User.new
  end

  def create
    
    @user=User.new(users_params)
    
    if @user.save
      flash[:success]='ユーザーを登録したよ'
      redirect_to @user
    else
      flash[:danger]='ユーザーの登録に失敗しました'
      render :new
    end
    
  end
  

  private
  def users_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
    
    def index
        if logged_in?
           @works = Work.all
        end
    end
    
    def show
        @work =  Work.find(params[:id])
    end
    def new
        @work= Work.new
    end
    
    def create
        @work = Work.new(work_params)
        if @work.save
            flash[:success]='work'
            # link_to 'work_path
            redirect_to @work
        else
            flash.now[:danger]='work'
            reder:new
        end
        
    end
    def edit
        @work= Work.find(params[:id])
    end
    def update
        @work= Work.find(params[:id])
        if @work.update(work_params)
            flash[:success]='成功しました'
            redirect_to @work
        else
            flash.now[:danger]='失敗しました'
            render :edit
        end
    end
    def destroy
         @work = Work.find(params[:id])
         @work.destroy

         flash[:success] = 'Message は正常に削除されました'
         redirect_to works_url
    end
    private
    def work_params
        params.require(:work).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        if @current_user.nil?
           @current_user = User.find_by(id: session[:user_id])
        else
           @current_user
        end
    end
    def logged_in?
        if current_user
            return true
        else
            return false
        end
    end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/
#{gravatar_id}
?s=
#{size}
"
  end
end

app/views/layouts/_flash_works.html.erb
<% flash.each do |work_type,work| %>
<div>
    <%= work %>
    
    
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">民</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="nsc">
      <span class="navbar-toggler-icon"></span>
    </button>



<div class='collapse navbar-collapse justify-content-end' id='nsc'>
  <ul class='navbar-nav'>
    
    <% if logged_in? %>
    <li class='nav-item'>
      <%= link_to '',users_path, class: 'nav-link' %>
    </li>
    <li class='nav-item dropdown'>
      <a href='#' class='nav-link dropdown-toggle' data-toggle='dropdown'>
        <%= current_user.name%>
      </a>
      <!--<ul class='dropdown-menu dropdown-menu-right'>-->
      <!--  <li class='dropdown-item'>-->
      <!--    <%= link_to '',users_path(current_user) %>-->
      <!--  </li>-->
      <!--  <li class='dropdown-divider'></li>-->
      <!--  <li class='dropdown-item'>logout</li>-->
      <!--</ul>-->
       <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item">
<%= link_to 'My profile', user_path(current_user) %>
</li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item">
<%= link_to 'Logout', logout_path, method: :delete %>
</li>
            </ul>
            
    </li>
    
    <% else%>
    
     <ul class="navbar-nav">
        <li class="nav-item">
<%= link_to '登録', signup_path, class: 'nav-link' %>
</li>
        <li class="nav-item">
<%= link_to 'ログイン', login_path, class: 'nav-link' %>
</li>
      </ul>
    
  <% end %>
    
  </ul>
</div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Microposts</title>
    
<%= csrf_meta_tags %>

    
<%= csp_meta_tag %>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    
<%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>
  <body>
   
      <div>
      <%= render 'layouts/navbar' %>
      
      
          <div class="container">
            
      <%= render 'layouts/flash_works' %>
      
      
            
      <%= yield %>
          </div>
  </body>
</html>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>

<% if current_user.following?(user) %>

<%= form_with(model: current_user.relationships.find_by(follow_id:user.id),local:true,method: :delete) do |f| %>

<%= hidden_field_tag :follow_id, user.id %>

<%= f.submit 'unfolow', class:'btn btn-danger btn-block' %>

<% end %>

<% else %>

<%= form_with(model: current_user.relationships.build, local:true) do |f| %>

<%= hidden_field_tag :follow_id,user.id %>

<%= f.submit 'follow', class:'btn btn-primary btn-block' %>

<% end %>

<% end %>

<% end %>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/toppages/index.html.erb
<% if logged_in? %>
<p>今ログインしているのは:<%= current_user.name %></p>


<% else %>

  <div class='center jumbotron'>
    <div class='text-center'>
        <h1>ようこそワールドへ</h1>
        <%= link_to '登録', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
</div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>

  <ul class="list-unstyled">
    
<% users.each do |user| %>

      <li class="media">
        <img class="mr-2 rounded" src="
<%= gravatar_url(user, { size: 50 }) %>
" alt="">
        <div class="media-body">
          <div>
            
<%= user.name %>

          </div>
          <div>
            <p>
<%= link_to 'View profile', user_path(user) %>
</p>
          </div>
        </div>
      </li>
    
<% end %>

  </ul>
  
<%= paginate users %>

<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class='text-cener'>
    <h1>登録しよう</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    
<%= form_with(model: @user, local: true) do |f| %>

      
      <div class="form-group">
        
<%= f.label :name, '名前' %>

        
<%= f.text_field :name, class: 'form-control' %>

      </div>

      <div class="form-group">
        
<%= f.label :email, 'メアド' %>

        
<%= f.email_field :email, class: 'form-control' %>

      </div>

      <div class="form-group">
        
<%= f.label :password, 'パスワード' %>

        
<%= f.password_field :password, class: 'form-control' %>

      </div>

      <div class="form-group">
        
<%= f.label :password_confirmation, 'もう一回' %>

        
<%= f.password_field :password_confirmation, class: 'form-control' %>

      </div>

      
<%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>

    
<% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">
<%= @user.name %>
</h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="
<%= gravatar_url(@user, { size: 500 }) %>
" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user:@user%>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="
<%= user_path(@user) %>
" class="nav-link 
<%= 'active' if current_page?(user_path(@user)) %>
">Microposts  <span class="badge badge-secondary">
<%= @count_microposts %>
</span></a></li>
      <li class="nav-item"><a href="#" class="nav-link">Followings</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Followers</a></li>
    </ul>
  </div>
</div>

app/views/works/edit.html.erb
<h2>新しい仕事を教えて</h2>


<%= form_with(model: @work, local: true) do |f| %>

  
<%= f.label :content, 'メッセージ' %>

  
<%= f.text_field :content %>


  
<%= f.submit '投稿' %>


<% end %>




<%= link_to '一覧に戻る', works_path %>
<%=link_to '仕事一覧に戻ろう', works_path%> 

app/views/works/index.html.erb
<% if logged_in? %>
        <p>今ログインしているのは:<%= current_user.name%></p>
        <h1>一覧</h1>
        <ul>
            <% @works.each do |work|%>
            <li>
                <%= link_to work.id, work %>
                <%= work.content%>
            </li>
        </ul>
        <% end %>
        <%= link_to '投稿する', new_work_path %>
        <%= link_to '一覧に戻ろう', works_path %>
        
<% else%>
        <div class='center jumbotron'>
            <div class='text-center'>
                <h1>ようこそ清水のワールドへようこそ</h1>
                <%= link_to 'に登録', signup_path, class: 'btn btn-lg btn-primary'%>
            </div>
        </div>

<% end %>

app/views/works/new.html.erb
<!--<h1>新しい仕事を教えてくれ</h1-->
<h2>新しい仕事を教えて</h2>


<%= form_with(model: @work, local: true) do |f| %>

  
<%= f.label :content, 'メッセージ' %>

  
<%= f.text_field :content %>


  
<%= f.submit '投稿' %>


<% end %>




<!--<%= link_to '一覧に戻る', works_path %>-->

<!--<h1>新しい仕事をしたい</h1>-->
<!--<%= form_with(model:@work, local:true) do |f| %>-->
<!--<%= f.label:content,'me'%>-->
<!--<%= f.text_field:content%>-->
<!--<%= f.submit 'tou'%>-->
<!--<% end %>-->
<!--<% link_to 'iti',works_path %>-->




  

  


  

app/views/works/show.html.erb
<h1>id:
<%= @work.id%>の仕事を紹介します!
</h1>
<p>
    
    <%= @work.content %>
    </p>
    <%=link_to '仕事一覧に戻ろう', works_path%>  <br> 
    <%=link_to 'この仕事やっぱ取り消し', @work,method: :delete %> <br>   <%=link_to '仕事の内容変える',edit_work_path %>
    <%= link_to 'このメッセージを削除する', @work, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
<%= link_to 'このメッセージを編集する', edit_work_path(@work) %>